{
 "cells": [
  {
   "cell_type": "code",
   "execution_count": 11,
   "id": "9b93fd1e",
   "metadata": {},
   "outputs": [],
   "source": [
    "import pythoncom\n",
    "from win32com.client import Dispatch, gencache\n",
    "\n",
    "#  Подключим константы API Компас\n",
    "kompas6_constants = gencache.EnsureModule(\"{75C9F5D0-B5B8-4526-8681-9903C567D2ED}\", 0, 1, 0).constants\n",
    "kompas6_constants_3d = gencache.EnsureModule(\"{2CAF168C-7961-4B90-9DA2-701419BEEFE3}\", 0, 1, 0).constants\n",
    "\n",
    "#  Подключим описание интерфейсов API5\n",
    "kompas6_api5_module = gencache.EnsureModule(\"{0422828C-F174-495E-AC5D-D31014DBBE87}\", 0, 1, 0)\n",
    "kompas_object = kompas6_api5_module.KompasObject(Dispatch(\"Kompas.Application.5\")._oleobj_.QueryInterface(kompas6_api5_module.KompasObject.CLSID, pythoncom.IID_IDispatch))\n",
    "\n",
    "#  Подключим описание интерфейсов API7\n",
    "kompas_api7_module = gencache.EnsureModule(\"{69AC2981-37C0-4379-84FD-5DD2F3C0A520}\", 0, 1, 0)\n",
    "application = kompas_api7_module.IApplication(Dispatch(\"Kompas.Application.7\")._oleobj_.QueryInterface(kompas_api7_module.IApplication.CLSID, pythoncom.IID_IDispatch))"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 12,
   "id": "caa9b09e",
   "metadata": {},
   "outputs": [],
   "source": [
    "Documents = application.Documents\n",
    "#  Получим активный документ\n",
    "kompas_document = application.ActiveDocument\n",
    "kompas_document_3d = kompas_api7_module.IKompasDocument3D(kompas_document)\n",
    "iDocument3D = kompas_object.ActiveDocument3D()\n",
    "iPart7 = kompas_document_3d.TopPart\n",
    "iPart = iDocument3D.GetPart(kompas6_constants_3d.pTop_Part)\n"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 13,
   "id": "7d50b131",
   "metadata": {},
   "outputs": [
    {
     "ename": "AttributeError",
     "evalue": "'NoneType' object has no attribute 'GetDefinition'",
     "output_type": "error",
     "traceback": [
      "\u001b[31m---------------------------------------------------------------------------\u001b[39m",
      "\u001b[31mAttributeError\u001b[39m                            Traceback (most recent call last)",
      "\u001b[36mCell\u001b[39m\u001b[36m \u001b[39m\u001b[32mIn[13]\u001b[39m\u001b[32m, line 22\u001b[39m\n\u001b[32m     20\u001b[39m iCollection.SelectByPoint(\u001b[32m20\u001b[39m, \u001b[32m0\u001b[39m, \u001b[32m0\u001b[39m)\n\u001b[32m     21\u001b[39m iEdge = iCollection.Last()\n\u001b[32m---> \u001b[39m\u001b[32m22\u001b[39m iEdgeDefinition = \u001b[43miEdge\u001b[49m\u001b[43m.\u001b[49m\u001b[43mGetDefinition\u001b[49m()\n\u001b[32m     23\u001b[39m iSketch = iEdgeDefinition.GetOwnerEntity()\n\u001b[32m     24\u001b[39m iDefinition.SetSketch(iSketch)\n",
      "\u001b[31mAttributeError\u001b[39m: 'NoneType' object has no attribute 'GetDefinition'"
     ]
    }
   ],
   "source": [
    "iSketch = iPart.NewEntity(kompas6_constants_3d.o3d_sketch)\n",
    "iDefinition = iSketch.GetDefinition()\n",
    "iPlane = iPart.GetDefaultEntity(kompas6_constants_3d.o3d_planeXOZ)\n",
    "iDefinition.SetPlane(iPlane)\n",
    "iSketch.Create()\n",
    "iDocument2D = iDefinition.BeginEdit()\n",
    "kompas_document_2d = kompas_api7_module.IKompasDocument2D(kompas_document)\n",
    "iDocument2D = kompas_object.ActiveDocument2D()\n",
    "\n",
    "obj = iDocument2D.ksCircle(10, 0, 10, 1)\n",
    "iDefinition.EndEdit()\n",
    "iDefinition.angle = 180\n",
    "iSketch.Update()\n",
    "iPart7 = kompas_document_3d.TopPart\n",
    "iPart = iDocument3D.GetPart(kompas6_constants_3d.pTop_Part)\n",
    "\n",
    "obj = iPart.NewEntity(kompas6_constants_3d.o3d_bossExtrusion)\n",
    "iDefinition = obj.GetDefinition()\n",
    "iCollection = iPart.EntityCollection(kompas6_constants_3d.o3d_edge)\n",
    "iCollection.SelectByPoint(20, 0, 0)\n",
    "iEdge = iCollection.Last()\n",
    "iEdgeDefinition = iEdge.GetDefinition()\n",
    "iSketch = iEdgeDefinition.GetOwnerEntity()\n",
    "iDefinition.SetSketch(iSketch)\n",
    "iExtrusionParam = iDefinition.ExtrusionParam()\n",
    "iExtrusionParam.direction = kompas6_constants_3d.dtNormal\n",
    "iExtrusionParam.depthNormal = 1\n",
    "iExtrusionParam.depthReverse = 0\n",
    "iExtrusionParam.draftOutwardNormal = False\n",
    "iExtrusionParam.draftOutwardReverse = False\n",
    "iExtrusionParam.draftValueNormal = 0\n",
    "iExtrusionParam.draftValueReverse = 0\n",
    "iExtrusionParam.typeNormal = kompas6_constants_3d.etBlind\n",
    "iExtrusionParam.typeReverse = kompas6_constants_3d.etBlind\n",
    "iThinParam = iDefinition.ThinParam()\n",
    "iThinParam.thin = False\n",
    "obj.name = \"Элемент выдавливания:1\"\n",
    "iColorParam = obj.ColorParam()\n",
    "iColorParam.ambient = 0.5\n",
    "iColorParam.color = 9474192\n",
    "iColorParam.diffuse = 0.6\n",
    "iColorParam.emission = 0.5\n",
    "iColorParam.shininess = 0.8\n",
    "iColorParam.specularity = 0.8\n",
    "iColorParam.transparency = 1\n",
    "obj.Create()\n",
    "iDocument2D = iDefinition.BeginEdit()\n",
    "kompas_document_2d = kompas_api7_module.IKompasDocument2D(kompas_document)\n",
    "iDocument2D = kompas_object.ActiveDocument2D()\n",
    "\n",
    "iDefinition.EndEdit()\n",
    "iPart7 = kompas_document_3d.TopPart\n",
    "iPart = iDocument3D.GetPart(kompas6_constants_3d.pTop_Part)\n",
    "\n",
    "iSketch = iPart.NewEntity(kompas6_constants_3d.o3d_sketch)\n",
    "iDefinition = iSketch.GetDefinition()\n",
    "iPlane = iPart.GetDefaultEntity(kompas6_constants_3d.o3d_planeXOZ)\n",
    "iDefinition.SetPlane(iPlane)\n",
    "iSketch.Create()\n",
    "iDocument2D = iDefinition.BeginEdit()\n",
    "kompas_document_2d = kompas_api7_module.IKompasDocument2D(kompas_document)\n",
    "iDocument2D = kompas_object.ActiveDocument2D()\n",
    "\n",
    "obj = iDocument2D.ksCircle(33.81297394414, 0, 9, 1)\n",
    "iLDimParam = kompas6_api5_module.ksLDimParam(kompas_object.GetParamStruct(kompas6_constants.ko_LDimParam))\n",
    "iDimDrawing = kompas6_api5_module.ksDimDrawingParam(iLDimParam.GetDPar())\n",
    "iDimDrawing.Init()\n",
    "iDimDrawing.ang = 0\n",
    "iDimDrawing.lenght = 0\n",
    "iDimDrawing.pl1 = False\n",
    "iDimDrawing.pl2 = False\n",
    "iDimDrawing.pt1 = 1\n",
    "iDimDrawing.pt2 = 1\n",
    "iDimDrawing.shelfDir = 0\n",
    "iDimDrawing.textBase = 0\n",
    "iDimDrawing.textPos = 0\n",
    "iLDimSource = kompas6_api5_module.ksLDimSourceParam(iLDimParam.GetSPar())\n",
    "iLDimSource.Init()\n",
    "iLDimSource.basePoint = 1\n",
    "iLDimSource.dx = 0\n",
    "iLDimSource.dy = 0\n",
    "iLDimSource.ps = 0\n",
    "iLDimSource.x1 = 50\n",
    "iLDimSource.y1 = 0\n",
    "iLDimSource.x2 = 0\n",
    "iLDimSource.y2 = 0\n",
    "iDimText = kompas6_api5_module.ksDimTextParam(iLDimParam.GetTPar())\n",
    "iDimText.Init(0)\n",
    "iDimText.bitFlag = 1\n",
    "iDimText.sign = 0\n",
    "iDimText.style = 3\n",
    "iDimText.stringFlag = False\n",
    "obj = iDocument2D.ksLinDimension(iLDimParam)\n",
    "iDefinition.EndEdit()\n",
    "iDefinition.angle = 180\n",
    "iSketch.Update()\n",
    "iPart7 = kompas_document_3d.TopPart\n",
    "iPart = iDocument3D.GetPart(kompas6_constants_3d.pTop_Part)\n",
    "\n",
    "obj = iPart.NewEntity(kompas6_constants_3d.o3d_bossRotated)\n",
    "iDefinition = obj.GetDefinition()\n",
    "iCollection = iPart.EntityCollection(kompas6_constants_3d.o3d_edge)\n",
    "iCollection.SelectByPoint(-36.6914989275, 0, 0)\n",
    "iEdge = iCollection.Last()\n",
    "iEdgeDefinition = iEdge.GetDefinition()\n",
    "iSketch = iEdgeDefinition.GetOwnerEntity()\n",
    "iDefinition.SetSketch(iSketch)\n",
    "iRotatedParam = iDefinition.RotatedParam()\n",
    "iRotatedParam.direction = kompas6_constants_3d.dtNormal\n",
    "iRotatedParam.angleNormal = 360\n",
    "iRotatedParam.angleReverse = 0\n",
    "iRotatedParam.toroidShape = True\n",
    "iRotated = kompas_object.TransferInterface(obj, kompas6_constants.ksAPI7Dual, 0)\n",
    "iAxis = iPart.GetDefaultEntity(kompas6_constants_3d.o3d_axisOZ)\n",
    "iRotatedAxis = kompas_object.TransferInterface(iAxis, kompas6_constants.ksAPI7Dual, 0)\n",
    "iRotated.Axis = iRotatedAxis\n",
    "iThinParam = iDefinition.ThinParam()\n",
    "iThinParam.thin = False\n",
    "obj.name = \"Элемент вращения:1\"\n",
    "iColorParam = obj.ColorParam()\n",
    "iColorParam.ambient = 0.5\n",
    "iColorParam.color = 9474192\n",
    "iColorParam.diffuse = 0.6\n",
    "iColorParam.emission = 0.5\n",
    "iColorParam.shininess = 0.8\n",
    "iColorParam.specularity = 0.8\n",
    "iColorParam.transparency = 1\n",
    "obj.Create()\n",
    "iDocument2D = iDefinition.BeginEdit()\n",
    "kompas_document_2d = kompas_api7_module.IKompasDocument2D(kompas_document)\n",
    "iDocument2D = kompas_object.ActiveDocument2D()\n",
    "\n",
    "obj = iDocument2D.ksCircle(49.993864298327, -0.783283167835, 10, 1)\n",
    "obj = iDocument2D.ksCircle(49.993864298327, -0.783283167835, 10, 1)\n",
    "iDefinition.EndEdit()"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "0be9dba3",
   "metadata": {},
   "outputs": [
    {
     "ename": "AttributeError",
     "evalue": "'<win32com.gen_py.69AC2981-37C0-4379-84FD-5DD2F3C0A520x0x1x0.IPart7 instance at 0x2497877080208>' object has no attribute 'GetDefaultEntity'",
     "output_type": "error",
     "traceback": [
      "\u001b[31m---------------------------------------------------------------------------\u001b[39m",
      "\u001b[31mAttributeError\u001b[39m                            Traceback (most recent call last)",
      "\u001b[36mCell\u001b[39m\u001b[36m \u001b[39m\u001b[32mIn[14]\u001b[39m\u001b[32m, line 28\u001b[39m\n\u001b[32m     25\u001b[39m part = doc3D.TopPart\n\u001b[32m     27\u001b[39m \u001b[38;5;66;03m# Получаем базовую плоскость и создаем смещённую\u001b[39;00m\n\u001b[32m---> \u001b[39m\u001b[32m28\u001b[39m basePlane = \u001b[43mpart\u001b[49m\u001b[43m.\u001b[49m\u001b[43mGetDefaultEntity\u001b[49m(kompas6_constants_3d.o3d_planeXOZ)\n\u001b[32m     29\u001b[39m offsetPlane = part.AddOffset(basePlane, center_y, \u001b[38;5;28;01mTrue\u001b[39;00m)\n\u001b[32m     31\u001b[39m \u001b[38;5;66;03m# Создаем эскиз на смещённой плоскости\u001b[39;00m\n",
      "\u001b[36mFile \u001b[39m\u001b[32mc:\\u4ebaENG\\Diplom-\\.venv\\Lib\\site-packages\\win32com\\client\\__init__.py:589\u001b[39m, in \u001b[36mDispatchBaseClass.__getattr__\u001b[39m\u001b[34m(self, attr)\u001b[39m\n\u001b[32m    587\u001b[39m args = \u001b[38;5;28mself\u001b[39m._prop_map_get_.get(attr)\n\u001b[32m    588\u001b[39m \u001b[38;5;28;01mif\u001b[39;00m args \u001b[38;5;129;01mis\u001b[39;00m \u001b[38;5;28;01mNone\u001b[39;00m:\n\u001b[32m--> \u001b[39m\u001b[32m589\u001b[39m     \u001b[38;5;28;01mraise\u001b[39;00m \u001b[38;5;167;01mAttributeError\u001b[39;00m(\u001b[33mf\u001b[39m\u001b[33m\"\u001b[39m\u001b[33m'\u001b[39m\u001b[38;5;132;01m{\u001b[39;00m\u001b[38;5;28mself\u001b[39m\u001b[38;5;132;01m!r}\u001b[39;00m\u001b[33m'\u001b[39m\u001b[33m object has no attribute \u001b[39m\u001b[33m'\u001b[39m\u001b[38;5;132;01m{\u001b[39;00mattr\u001b[38;5;132;01m}\u001b[39;00m\u001b[33m'\u001b[39m\u001b[33m\"\u001b[39m)\n\u001b[32m    590\u001b[39m \u001b[38;5;28;01mreturn\u001b[39;00m \u001b[38;5;28mself\u001b[39m._ApplyTypes_(*args)\n",
      "\u001b[31mAttributeError\u001b[39m: '<win32com.gen_py.69AC2981-37C0-4379-84FD-5DD2F3C0A520x0x1x0.IPart7 instance at 0x2497877080208>' object has no attribute 'GetDefaultEntity'"
     ]
    }
   ],
   "source": [
    "# -*- coding: utf-8 -*-\n",
    "import pythoncom\n",
    "from win32com.client import Dispatch, gencache\n",
    "\n",
    "# Подключение API Компас 3D\n",
    "kompas6_constants = gencache.EnsureModule(\"{75C9F5D0-B5B8-4526-8681-9903C567D2ED}\", 0, 1, 0).constants\n",
    "kompas6_constants_3d = gencache.EnsureModule(\"{2CAF168C-7961-4B90-9DA2-701419BEEFE3}\", 0, 1, 0).constants\n",
    "kompas_api7 = gencache.EnsureModule(\"{69AC2981-37C0-4379-84FD-5DD2F3C0A520}\", 0, 1, 0)\n",
    "\n",
    "# Получаем приложение Компас\n",
    "application = kompas_api7.IApplication(Dispatch(\"Kompas.Application.7\"))\n",
    "Documents = application.Documents\n",
    "\n",
    "# Основной цикл — создаем 3 модели\n",
    "for i in range(3):\n",
    "    # Параметры окружности\n",
    "    center_x = i * 30        # X-координата центра\n",
    "    center_y = 0             # Смещение по Y (вдоль оси Y — это высота от плоскости XOZ)\n",
    "    center_z = 0             # Z-координата центра\n",
    "    radius = 10 + i * 5      # Радиус окружности\n",
    "\n",
    "    # Создаем новый документ\n",
    "    doc = Documents.AddWithDefaultSettings(kompas6_constants.ksDocumentPart, True)\n",
    "    doc3D = kompas_api7.IKompasDocument3D(doc)\n",
    "    part = doc3D.TopPart\n",
    "\n",
    "    # Получаем базовую плоскость и создаем смещённую\n",
    "    part.GetEnt\n",
    "    basePlane = part.GetDefaultEntity(kompas6_constants_3d.o3d_planeXOZ)\n",
    "    offsetPlane = part.AddOffset(basePlane, center_y, True)\n",
    "\n",
    "    # Создаем эскиз на смещённой плоскости\n",
    "    sketchEntity = part.NewEntity(kompas6_constants_3d.o3d_sketch)\n",
    "    sketchDef = sketchEntity.GetDefinition()\n",
    "    sketchDef.SetPlane(offsetPlane)\n",
    "    sketchEntity.Create()\n",
    "\n",
    "    # Рисуем окружность в эскизе\n",
    "    sketch2D = sketchDef.BeginEdit()\n",
    "    sketch2D.ksCircle(center_x, center_z, radius, 1)\n",
    "    sketchDef.EndEdit()\n",
    "\n",
    "    # Создаем тело вращением\n",
    "    rotateEntity = part.NewEntity(kompas6_constants_3d.o3d_bossRotated)\n",
    "    rotateDef = rotateEntity.GetDefinition()\n",
    "    rotateDef.SetSketch(sketchEntity)\n",
    "\n",
    "    rotateParams = rotateDef.RotatedParam()\n",
    "    rotateParams.direction = kompas6_constants_3d.dtNormal\n",
    "    rotateParams.angleNormal = 360\n",
    "    rotateParams.angleReverse = 0\n",
    "    rotateParams.toroidShape = False  # True — если нужен тор\n",
    "\n",
    "    rotateEntity.Create()\n",
    "\n",
    "    # Сохраняем модель\n",
    "    path = fr\"C:\\u4ebaENG\\Diplom-\\DSet\\Spins\\ring_{i}.m3d\"\n",
    "    doc.SaveAs(path)\n",
    "\n",
    "print(\"Генерация завершена.\")"
   ]
  }
 ],
 "metadata": {
  "kernelspec": {
   "display_name": ".venv",
   "language": "python",
   "name": "python3"
  },
  "language_info": {
   "codemirror_mode": {
    "name": "ipython",
    "version": 3
   },
   "file_extension": ".py",
   "mimetype": "text/x-python",
   "name": "python",
   "nbconvert_exporter": "python",
   "pygments_lexer": "ipython3",
   "version": "3.12.9"
  }
 },
 "nbformat": 4,
 "nbformat_minor": 5
}
